Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,34 +9,33 @@ jobs:
   scrape:
     runs-on: ubuntu-latest
     steps:
-    - name: Check out repository
-      uses: actions/checkout@v4
+      - name: Check out repository
+        uses: actions/checkout@v4
 
-    - name: Set up Python
-      uses: actions/setup-python@v4
-      with:
-        python-version: '3.10'
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.10'
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
 
-    - name: Run scraper script
-      env:
-        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
-        LINE_TARGET_ID: ${{ secrets.LINE_TARGET_ID }}
-      run: python scraper.py
+      - name: Run scraper script
+        env:
+          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
+          LINE_TARGET_ID: ${{ secrets.LINE_TARGET_ID }}
+        run: python scraper.py
 
-    - name: Commit and push if changed
-  run: |
-    # ตรวจสอบก่อนว่าไฟล์ last_data.txt ถูกสร้างขึ้นมาหรือไม่
-    if [ -f last_data.txt ]; then
-      git config --local user.email "action@github.com"
-      git config --local user.name "GitHub Action"
-      git add last_data.txt
-      git diff --quiet && git diff --staged --quiet || (git commit -m "Update last water data" && git push)
-    else
-      echo "last_data.txt not found, skipping commit."
-    fi
-    
+      - name: Commit and push if changed
+        run: |
+          # ตรวจสอบก่อนว่าไฟล์ last_data.txt ถูกสร้างขึ้นมาหรือไม่
+          if [ -f last_data.txt ]; then
+            git config --local user.email "action@github.com"
+            git config --local user.name "GitHub Action"
+            git add last_data.txt
+            git diff --quiet && git diff --staged --quiet || (git commit -m "Update last water data" && git push)
+          else
+            echo "last_data.txt not found, skipping commit."
+          fi
