Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,8 +29,13 @@ jobs:
       run: python scraper.py
 
     - name: Commit and push if changed
-      run: |
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git add last_data.txt
-        git diff --quiet && git diff --staged --quiet || (git commit -m "Update last water data" && git push)
+  run: |
+    # ตรวจสอบก่อนว่าไฟล์ last_data.txt ถูกสร้างขึ้นมาหรือไม่
+    if [ -f last_data.txt ]; then
+      git config --local user.email "action@github.com"
+      git config --local user.name "GitHub Action"
+      git add last_data.txt
+      git diff --quiet && git diff --staged --quiet || (git commit -m "Update last water data" && git push)
+    else
+      echo "last_data.txt not found, skipping commit."
+    fi
